[build]
  publish = "."

[[redirects]]
  from = "/"
  to   = "/palmistry/"
  status = 301

[[redirects]]
  from = "/palmistry"
  to   = "/palmistry/index.html"
  status = 200

[[redirects]]
  from = "/quamtsm"
  to   = "/quamtsm/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  Cache-Control = "public, max-age=0, s-maxage=300, must-revalidate"
