/* ---------------------------------------------------------
   THE SEED · TRUTH OUTPUT ENGINE
   Combines Palm Reading + Karma Reading into final text
----------------------------------------------------------*/

export function renderTruth(palmReading, karmaReading) {
  let finalText = "";

  finalText += "🧿 THE SEED — Final Palmistry Report\n";
  finalText += "-----------------------------------------\n\n";

  // Palm Reading Section
  finalText += "✋ Palm Reading:\n";
  finalText += palmReading ? palmReading + "\n\n" : "No palm data.\n\n";

  // Karma Reading Section
  finalText += "🕉 Karma Analysis:\n";
  finalText += karmaReading ? karmaReading + "\n\n" : "No karma data.\n\n";

  // Universal Closing Message
  finalText += "-----------------------------------------\n";
  finalText += "🌟 This reading was generated by THE SEED — Quantum Palmistry AI.\n";
  finalText += "May wisdom guide your path.\n";

  return finalText;
}
