 const $ = id => document.getElementById(id);
const statusEl = $("status");
const reportBox = $("reportBox");
const leftVid = $("vidLeft"), rightVid = $("vidRight");
const leftCv = $("canvasLeft"), rightCv = $("canvasRight");

function msg(t, ok = true) {
  statusEl.textContent = t;
  statusEl.style.color = ok ? "#16f0a7" : "#ff6b6b";
}

// === Camera ===
async function startCam(side) {
  const video = side === "left" ? leftVid : rightVid;
  try {
    const stream = await navigator.mediaDevices.getUserMedia({
      video: { facingMode: "environment" },
      audio: false
    });
    video.srcObject = stream;
    await video.play();
    msg(`${side} camera started ✅`);
  } catch (e) {
    msg(`Camera error: ${e.message}`, false);
  }
}

// === Capture + Analyze ===
async function analyze(side) {
  const video = side === "left" ? leftVid : rightVid;
  const canvas = side === "left" ? leftCv : rightCv;
  const ctx = canvas.getContext("2d");

  canvas.width = video.videoWidth;
  canvas.height = video.videoHeight;
  ctx.drawImage(video, 0, 0, canvas.width, canvas.height);

  msg(`Analyzing ${side} hand...`);
  const data = ctx.getImageData(0, 0, canvas.width, canvas.height);

  const brightness = avgBrightness(data.data);
  const clarity = edgeStrength(data.data);

  // === 8-line AI interpretations ===
  const lines = {
    life: interpretLife(clarity, brightness),
    heart: interpretHeart(clarity, brightness),
    fate: interpretFate(brightness, clarity),
    head: interpretHead(brightness, clarity),
    sun: interpretSun(clarity, brightness),
    marriage: interpretMarriage(clarity, brightness),
    health: interpretHealth(brightness, clarity),
    manikanda: interpretManikanda(clarity, brightness)
  };

  const report = `
📜 Palmistry Report (${side} hand)
──────────────────────────────
🌿 Life Line : ${lines.life}
💓 Heart Line : ${lines.heart}
⚖️ Fate Line : ${lines.fate}
🧠 Head Line : ${lines.head}
☀️ Sun Line : ${lines.sun}
💍 Marriage Line : ${lines.marriage}
💎 Health Line : ${lines.health}
🔱 Manikanda Line : ${lines.manikanda}
──────────────────────────────
Overall Clarity: ${clarity.toFixed(2)} | Light Balance: ${brightness.toFixed(2)}
✨ Generated by Buddhi AI Palm Analyzer
`;

  reportBox.textContent = report;
  msg(`✅ ${side} hand analysis complete`);
  speak(report);
}

// === Helpers ===
function avgBrightness(d) {
  let s = 0;
  for (let i = 0; i < d.length; i += 4) s += (d[i] + d[i + 1] + d[i + 2]) / 3;
  return s / (d.length / 4) / 255;
}
function edgeStrength(d) {
  let e = 0;
  for (let i = 0; i < d.length; i += 16)
    e += Math.abs(d[i] - d[i + 4]) + Math.abs(d[i + 1] - d[i + 5]);
  return e / (d.length / 16) / 255;
}

// === Line Interpretations ===
function interpretLife(c, b) {
  if (c > 0.45 && b < 0.5) return "Strong vitality and balanced energy.";
  if (c < 0.3) return "Energy fluctuations; rest is essential.";
  return "Moderate strength and endurance.";
}
function interpretHeart(c, b) {
  if (b > 0.6) return "Deep emotional sensitivity and intuition.";
  if (c > 0.5) return "Compassionate and gentle heart.";
  return "Calm, reserved emotions.";
}
function interpretFate(b, c) {
  if (c > 0.55) return "Disciplined path with karmic purpose.";
  if (b > 0.55) return "Creative destiny, freedom-loving.";
  return "Unfolding life path; reflection advised.";
}
function interpretHead(b, c) {
  if (b < 0.4 && c > 0.45) return "Logical, steady thinker.";
  if (b > 0.6) return "Imaginative and intuitive mind.";
  return "Balanced intellect with spiritual insight.";
}
function interpretSun(c, b) {
  if (b > 0.6) return "Bright charisma and leadership light.";
  if (c < 0.4) return "Talent hidden; seek self-expression.";
  return "Calm, radiant personality.";
}
function interpretMarriage(c, b) {
  if (b > 0.5) return "Devoted love, loyalty in partnership.";
  if (c < 0.35) return "Love energy needs patience and faith.";
  return "Balanced affection and trust.";
}
function interpretHealth(b, c) {
  if (c < 0.3) return "Energy strain — protect body and mind.";
  if (b > 0.6) return "Excellent vitality, healing aura.";
  return "Good balance of health and rest.";
}
function interpretManikanda(c, b) {
  if (c > 0.55) return "Spiritual awakening line visible — higher insight emerging.";
  if (b > 0.55) return "Rising spiritual sensitivity — potential for deep meditation.";
  return "Dormant spiritual line; focus on devotion and truth.";
}

// === Voice Narration ===
function speak(txt) {
  try {
    const synth = window.speechSynthesis;
    const u = new SpeechSynthesisUtterance(txt);
    u.lang = "en-US"; u.rate = 1; u.pitch = 1.1;
    synth.cancel(); synth.speak(u);
  } catch (e) { console.warn("Speech error", e); }
}

// === Bind ===
$("startLeft").onclick = () => startCam("left");
$("startRight").onclick = () => startCam("right");
$("captureLeft").onclick = () => analyze("left");
$("captureRight").onclick = () => analyze("right");

// === Init ===
(async () => {
  if (!navigator.mediaDevices) msg("Camera not supported ❌", false);
  else msg("Ready. Click Start → Analyze ✨");
})();
