services:
  - type: web
    name: ceed-api
    env: node
    plan: free
    branch: main
    rootDir: render
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
