// modules/analyzer.js — V8.3 Symbolic Reasoner Edition
// =====================================================
import { emit } from "./bus.js";

// === Symbolic Reasoner Core (V8.3) ===
function symbolicReasoner(clarity, brightness) {
  const findings = [];

  if (clarity > 0.55 && brightness > 0.55)
    findings.push("Lines are luminous and stable — harmony between karmic and present energies.");
  if (clarity < 0.35 && brightness > 0.6)
    findings.push("Spiritual potential high, but worldly restlessness present.");
  if (clarity > 0.45 && brightness < 0.4)
    findings.push("Deep-rooted karmic memory influencing physical life force.");
  if (Math.abs(clarity - brightness) < 0.05)
    findings.push("Balanced duality between past and present lives — transformation imminent.");
  if (clarity > 0.6)
    findings.push("Strong intuitive foresight; seeker of hidden truths.");
  if (brightness < 0.3)
    findings.push("Shadowed subconscious; meditation and faith advised.");

  findings.push("🔹 Cross pattern near Life Line → Major destiny reconfiguration.");
  findings.push("⭐ Star near Fate Line → Sudden recognition or spiritual elevation.");
  findings.push("⚡ Fork in Head Line → Dual paths of logic and imagination.");
  findings.push("🌙 Island in Heart Line → Emotional sensitivity requiring healing.");
  findings.push("🔥 Chain marks along Sun Line → Creative obstacles transforming into wisdom.");
  findings.push("💧 Break on Health Line → Temporary imbalance, rest recommended.");
  findings.push("🔱 Rising Manikanda Line → Divine awakening through karma purification.");

  return findings.join("\n");
}

function analyzeWithSymbolic(side, clarity, brightness) {
  const reasonText = symbolicReasoner(clarity, brightness);
  const combined = `\n\n🧩 Symbolic Reasoning (${side} hand)\n──────────────────────────────\n${reasonText}\n──────────────────────────────\n🕊️ The balance of karma and present destiny converges within the seeker.\n`;
  return combined;
}

// === Main Analyzer Core ===
export async function runAnalysis({ hand = "left" } = {}) {
  const start = performance.now();
  emit("analyzer:status", { level: "info", msg: `start ${hand}` });

  // 1) preprocess
  emit("analyzer:step", { tag: "preprocess", msg: "denoise + normalize" });

  // demo metrics
  emit("analyzer:metric", { key: `${hand}.contrast`, val: 0.82 });
  emit("analyzer:metric", { key: `${hand}.edges`, val: 1532 });

  // 2) model inference
  emit("analyzer:step", { tag: "inference", msg: "onnx run" });

  const modelOut = {
    lines: {
      life:  { length: 82, clarity: 0.88, slope: 9,  breaks: 0, crosses: 1 },
      head:  { length: 76, clarity: 0.74, slope: 14, breaks: 1, crosses: 0 },
      heart: { length: 69, clarity: 0.79, slope: 7,  breaks: 0, crosses: 1 }
    }
  };

  emit("analyzer:metric", { key: `${hand}.life.length`, val: modelOut.lines.life.length });
  emit("analyzer:metric", { key: `${hand}.head.slope`, val: modelOut.lines.head.slope });
  emit("analyzer:metric", { key: `${hand}.heart.clarity`, val: modelOut.lines.heart.clarity });

  // 3) fusion (rules + model)
  emit("analyzer:step", { tag: "fusion", msg: "ruleset merge" });

  const fusion = {
    summary: "Strong vitality, analytical mind, sincere emotions.",
    all: [
      { id: "life-slope-up", weight: 0.70, meaning: "Optimism & vitality" },
      { id: "head-length-long", weight: 0.80, meaning: "Analytical depth" },
      { id: "heart-clarity-strong", weight: 0.90, meaning: "Emotional stability" }
    ]
  };

  const score = (fusion.all.reduce((a, b) => a + b.weight, 0) / fusion.all.length).toFixed(2);
  emit("analyzer:metric", { key: `${hand}.fusion.score`, val: Number(score) });

  // Create report box dynamically (safe fallback)
  const reportBox = document.getElementById("reportBox");
  const clarity = ((modelOut.lines.life.clarity + modelOut.lines.head.clarity + modelOut.lines.heart.clarity) / 3).toFixed(2);
  const brightness = (0.4 + Math.random() * 0.3).toFixed(2);

  const report = `📜 Palmistry Report (${hand} hand)\n──────────────────────────────
🌿 Life Line: Optimism & vitality.
🧠 Head Line: Analytical depth.
💗 Heart Line: Emotional stability.
──────────────────────────────
Overall clarity: ${clarity} | Light balance: ${brightness}\n✨ Generated by Buddhi AI Palm Analyzer`;

  // 4) symbolic reasoning integration
  const reasonReport = analyzeWithSymbolic(hand, clarity, brightness);
  reportBox.textContent = report + reasonReport;

  const ms = (performance.now() - start).toFixed(0);
  emit("analyzer:status", { level: "ok", msg: `done ${hand} (${ms} ms)` });

  return fusion;
}
