// modules/report.js — Sathyadarshana Quantum Palm Analyzer · V10.2
import { on, emit } from './bus.js';

on("vision:ready", ({ side, result }) => {
  const reportBox = document.getElementById("reportBox");
  const status = document.getElementById("status");

  // 🪶 Render final styled report
  reportBox.innerHTML = `
    <div style="border:1px solid #16f0a7; border-radius:12px; padding:14px; background:#101820;">
      <h3 style="color:#00e5ff; text-shadow:0 0 6px #00e5ff;">${side.toUpperCase()} HAND REPORT</h3>
      <p style="line-height:1.6em; font-size:1.05em;">${result}</p>
      <p style="color:#16f0a7; font-size:0.9em; margin-top:8px;">
        🕉️ Generated by Sathyadarshana Quantum Analyzer V10.2
      </p>
    </div>
  `;

  status.textContent = `🧠 Insight ready for ${side} hand`;

  // Emit event for voice narration
  emit("report:ready", { side, text: cleanText(result) });
});

// === Clean HTML tags before speech synthesis ===
function cleanText(html) {
  const div = document.createElement("div");
  div.innerHTML = html;
  return div.textContent || div.innerText || "";
}
