export function generatePalmReport(data, mode="mini"){
  const {hand="Left",density=50,name="Seeker"}=data;
  const path=hand==="Left"?"past":"present";
  const densityDesc=density>70?"clear and defined":
                    density>40?"balanced and reflective":"soft and subtle";

  if(mode==="mini"){
    return `
<h3>🪶 ${hand} Hand ${path==="past"?"Karmic":"Life"} Summary</h3>
<p>
Dear ${name}, your ${hand.toLowerCase()} hand shows a ${densityDesc} network of lines,
revealing ${path==="past"?"deep karmic roots":"active destiny unfolding"}.
Life, Head, Heart, and Fate lines unite to form a balanced spiritual pattern.
</p>
<p><i>– Buddhi AI · Sathyadarshana Quantum Palm Analyzer V6.0</i></p>`;
  }

  return `
<h2>🌕 ${hand} Hand Deep Soul Analysis</h2>
${["Life","Head","Heart","Fate","Sun","Health","Marriage","Bracelet"].map((ln,i)=>`
<h3>${i+1}. ${ln} Line</h3>
<p>Insight on ${ln.toLowerCase()} aspects: balanced ${ln==="Life"?"vitality":"energy"}, karmic resonance, and soul growth.</p>
`).join("")}
<p><i>– Generated by Buddhi AI · Final Version V6.0</i></p>`;
}
